name: Create Release

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  release:
    uses: PlainsightAI/gh-actions/.github/workflows/filter-release-premium.yaml@main
    permissions:
      contents: write
      id-token: write
      actions: read
      pull-requests: read
    with:
      python_versions: '["3.11", "3.12"]'
      source-paths: |
        filter_*/**
        pyproject.toml
        Dockerfile*
        requirements*.txt
    secrets:
      TESTMO_PLAINSIGHT_URL: ${{ secrets.TESTMO_PLAINSIGHT_URL }}
      TESTMO_PLAINSIGHT_TESTING_API_KEY: ${{ secrets.TESTMO_PLAINSIGHT_TESTING_API_KEY }}
      GH_DOCS_PUBLISHING_TOKEN: ${{ secrets.GH_DOCS_PUBLISHING_TOKEN }}
