# Ensure RELEASE.md and VERSION file are updated in PRs
name: Version Check

on:
  pull_request:
    branches: [main]

jobs:
  check-release-log:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check RELEASE.md
        uses: PlainsightAI/gh-actions/check-release-log@main
